Changes to food hygiene qualification
wearefuturegov/tell-us-who-you-employ pull request #15
Opened 2022-05-03 16:18 UTC by gabimartini

trello issue: https://trello.com/c/RrFI604
<img width="1153" alt="Screenshot 2022-05-03 at 16 54 08" src="https://user-images.githubusercontent.com/49984490/166493447-0393a1aa-5646-407b-854e-8e0be2b3a771.png">
6

2022-05-04 14:25 UTC, em-cd requested changes
Nicely done @gabimartini!

The only thing which is missing from this is to add to the import script so that we set the new `has_food_hygiene` field based on whether the skills column in the CSV contains 'Food Hygiene'. Happy to chat about this if it's easier!

2022-05-04 14:25 UTC, em-cd commented on db/schema.rb
> +    t.string "item_type"
This one has snuck in again! 😄

2022-05-04 14:45 UTC, gabimartini commented on db/schema.rb
> +    t.string "item_type"
:woman-facepalming: Fixed!

2022-05-06 09:37 UTC, em-cd approved these changes
LGTM! 🎉

2022-05-06 09:42 UTC, gabimartini commented on db/schema.rb
> +    t.string "item_type"
No way!!! I will remove now haha

2022-05-06 09:47 UTC, gabimartini commented on db/schema.rb
> +    t.string "item_type"
done!

2022-05-06 10:05 UTC, em-cd commented on db/schema.rb
> +    t.string "item_type"
How weird, I didn't write that message today but it posted it again 😂

2022-05-06 10:18 UTC, merged